describe('gaxiosErrorHandler', () => {
    test.todo('Should call next with error when it is not a GaxiosError');
    test.todo(
        'Should return Bad Request when error message is "Invalid Input: Filter"'
    );
    test.todo(
        'Should return Unauthorized when error message is "Invalid Credentials"'
    );
    test.todo(
        'Should return Unauthorized when error message is "invalid_grant"'
    );
    test.todo(
        'Should return Not Found when error message is "Resource has been deleted"'
    );
    test.todo('Should return Not Found when error message is "Not Found"');
    test.todo(
        'Should return Internal Server Error when error message is something else'
    );
});
